# This Dockerfile builds the API only.

FROM python:slim
WORKDIR /app

COPY api/requirements_cpu.txt api/api.py api/.flaskenv ./
RUN mkdir -p ./static/files
RUN pip install -r ./requirements_cpu.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "api:app"]
